<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Feature_Request_Portal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Feature_Request_Portal.Domain\Feature_Request_Portal.Domain.csproj" />
    <ProjectReference Include="..\Feature_Request_Portal.Application.Contracts\Feature_Request_Portal.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.6.0" />
  </ItemGroup>

</Project>
